# -*- coding: utf-8 -*-
"""Deployment of Brain Tumor model on Streamlit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HAN-IHK4sJnr3bOFFh5NsO7XUxTjbEd_
"""

!pip install streamlit

!pip install pyngrok==4.1.1

# Commented out IPython magic to ensure Python compatibility.
# %%writefile brain_tumor.py
# import streamlit as st
# import numpy as np
# import tensorflow as tf
# from PIL import Image, ImageOps
# 
# @st.cache(allow_output_mutation= True)
# 
# def load_model():
#   model = tf.keras.models.load_model("/content/drive/MyDrive/Brain_Tumor_Detection/brain_tumor_model_CNN.h5")
#   return model
# 
# model = load_model()
# st.write("## Brain Tumor Classification")
# 
# file = st.file_uploader("Please upload an Brain Tumor image", type = ['png', 'jpg', 'jpeg'])
# 
# def import_and_predict(image_data, model):
#   size = (64,64)
#   image = ImageOps.fit(image_data, size , Image.ANTIALIAS)
#   img = np.asarray(image)
#   img = img/255.0
#   img_reshape = img[np.newaxis,...]
#   prediction = model.predict(img_reshape)
# 
#   return prediction
# 
# if file is None:
#   st.text("Please upload an image file...")
# 
# else:
#   image = Image.open(file)
#   st.image(image, use_column_width= True)
#   predictions = import_and_predict(image, model)
#   class_names = ['No Tumor', 'Have Tumor']
#   if np.argmax(predictions) == 0:
#     st.write("# Great!!!, You don't have Brain Tumor Disease.")
#   else:
#     st.write("# Sorry, You have Brain Tumor Disease, Kindly contact your doctor.")
#

#!ngrok authtoken XXXXXXXXXXXXXXXXXXXXXXXXXXX

!nohup streamlit run brain_tumor.py &

from pyngrok import ngrok
public_url = ngrok.connect(port = '8501')

public_url

#ngrok.kill()

